"""
Django settings for prospeccionsalesforce project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from isapilib.core.utilities import to_bool

load_dotenv('../.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$q&h5kwfz%q^*ocr(hbngrwa33-5(iyeduy#9!6ca(ipasz%)&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = to_bool(os.getenv("ISAPI-DEBUG", False))

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework',
    'api',
    'isapilib',
    'oauth2_provider',
]

MIDDLEWARE = []

ROOT_URLCONF = 'prospeccionsalesforce.urls'

WSGI_APPLICATION = 'prospeccionsalesforce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("ISAPI-ENGINE"),
        'NAME': os.getenv("ISAPI-NAME"),
        'USER': os.getenv("ISAPI-USER"),
        'PASSWORD': os.getenv("ISAPI-PASSWORD"),
        'HOST': os.getenv("ISAPI-HOST"),
        'PORT': os.getenv("ISAPI-PORT"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'isapilib.UserAPI'

DATABASE_ROUTERS = ['prospeccionsalesforce.router.BranchRouter']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'isapilib.auth.permissions.IsapilibPermission',
    ),
}
INTERFAZ_NAME = 'ProspeccionSalesForce'
URL_DOCUMENTATION = 'itlabv2.intelisis-solutions.com:8008/'
MAX_NUMBER_LOGS = 2000
